export enum AgentType {
  CODEX = 'CODEX',
  CLAUDE = 'CLAUDE',
  CURSOR = 'CURSOR'
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum TaskType {
  FRONTEND_REFACTOR = 'FRONTEND_REFACTOR',
  BUG_FIX = 'BUG_FIX',
  LARGE_REFACTOR = 'LARGE_REFACTOR',
  NEW_FEATURE = 'NEW_FEATURE',
  TEST_WRITING = 'TEST_WRITING',
  DOCUMENTATION = 'DOCUMENTATION'
}

export enum SandboxMode {
  WORKSPACE_WRITE = 'WORKSPACE_WRITE',
  READ_ONLY = 'READ_ONLY',
  DANGER_FULL_ACCESS = 'DANGER_FULL_ACCESS'
}

export enum ApprovalPolicy {
  ON_REQUEST = 'ON_REQUEST',
  AUTO_APPROVE = 'AUTO_APPROVE',
  NEVER = 'NEVER'
}

export enum RiskReportType {
  PERMISSION_ASSESS = 'PERMISSION_ASSESS',
  COMMAND_AUDIT = 'COMMAND_AUDIT',
  PREFLIGHT_CHECK = 'PREFLIGHT_CHECK',
  GIT_DIFF_AUDIT = 'GIT_DIFF_AUDIT',
  MARKDOWN_REPORT = 'MARKDOWN_REPORT',
  PROJECT_SCAN = 'PROJECT_SCAN'
}

export enum PreflightCheckStatus {
  PASS = 'PASS',
  WARN = 'WARN',
  FAIL = 'FAIL'
}
